services:
  db:
    image: postgres:16-alpine
    container_name: boardgame_db
    restart: always
    environment:
      POSTGRES_DB: boardgameconnect_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: